### ISSUE TITLE
Remove friction from FREE user onboarding

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#163]
This morning, I've forced myself to go through the whole "_discovering and using Backpack for the first time_" experience. To look at what we offer and how we do things... from the point of view of a person who's just discovered Backpack now, and has never used it.

I'm... both disappointed that we haven't seen some things until now... and excited, because most of what I've found is low-hanging fruit. So **with very little dev/design time, we can GREATLY improve our onboarding**.

I'll document my experience here, then add individual issues for each TODO, so that **we do them all, until Aug 1st. Yes, that's right. This become priority numero uno!** In order to get more users, there's nothing more important than offering a top-notch onboarding experience.

# Landed on website (homepage)

- [x] design looks a bit dated / stock; no video?! bleah... you make me work for the info, gotta scroll... ok; https://github.com/Laravel-Backpack/backpackforlaravel.com/issues/13
- [x] why no Github logo and link? I expected it to be there, since this is a free Github repo; otherwise, I'm starting to think it's a SaaS or something; @tabacitu 
- [ ] love the demo! super useful; don't understand what half of these things are, though; I landed on Monsters by chance, shouldn't this be your most prominent page, since it includes so many features?
- [x] I'm back to homepage; the brand logos didn't stand out to me; didn't even see them, tbh; why not add a title, and more logos? and maybe make 'em move, so we see there are many many big brands using Backpack? or perhaps make them color instead of monochrome? @tabacitu 
- [ ] operations section is pretty nice, but too long; i like the images, but don't want to scroll through the whole thing; could put this into tabs or smth; @tabacitu 
- [ ] impossible section looks unimpressive; @tabacitu 
- [ ] advanced UX section looks amateur-ish, because of the image; @tabacitu 
- [ ] tools & services section looks amateur-ish for some reason... I think it's the GIF, perhaps a short video instead? @tabacitu 
- [x] why say 1M downloads when you have 1.5M? @tabacitu 
- [x] testimonials aren't visible AT ALL; when they're super-important, they could have made me pause, read, and say "_ok let me give this a chance_"; add photos; make 'em prettier; add full names, positions and companies, for legitimacy; or get some bigger names saying good things about Backpack; https://github.com/Laravel-Backpack/backpackforlaravel.com/issues/148
- [x] footer buttons should be "Get Started" and "Demo"; with "Get Started" leading to the docs ([Introduction](https://backpackforlaravel.com/docs)); @tabacitu 
- [ ] does not answer the question - "_how maintained is this? can I trust it?_"

# Have created a user

- [x] the Getting Started page is useless; we have the same info in the docs; let's capitalize on the fact that they have an account now, and walk them through all things they should learn about using Backpack, in order to be comfortable using it (aka learning checklist); see https://github.com/Laravel-Backpack/backpackforlaravel.com/issues/29#issuecomment-1190310162 until we do that, we should NOT be sending people to that page; it's added friction to create an account; we should send them to the documentation's Getting Started page; @tabacitu 

# Have gotten to the Installation documentation page

- [x] why do I need to install the generators separately?! why doesn't the install command ask me if I want the generators installed? or just install it, without asking?! @promatik in https://github.com/Laravel-Backpack/CRUD/pull/4559
- [x] why doesn't the install command ask me if I want PRO too?! @promatik in https://github.com/Laravel-Backpack/CRUD/pull/4559
- [x] why doesn't the install command ask me if I want to create an admin? that's the first thing I'll do, do I really have to go through the Registration screen? @promatik in https://github.com/Laravel-Backpack/CRUD/pull/4559
- [x] why doesn't the installer say "_Successfully installed. You can now go to http://your-local-domain.com/admin to log in._"? It knows both the domain name and the prefix, why don't you tell me exactly what to do next, right there? @promatik in https://github.com/Laravel-Backpack/CRUD/pull/4559

# Have gotten to an empty dashboard page

- [x] what do I do now?! why no tips, tutorial or next steps?
- [x] #170

**Comment by tabacitu** [comment]
Also, going through the process above, I've realise what our most important touchpoints are. What does a visitor see, and interact with, before they get to the "AHA" moment?

- homepage
- docs (introduction page)
    - video course (or)
    - text course (or)
    - drip email course
- installation docs page
- `php artisan backpack:install`
- login page
- empty dashboard
- `php artisan backpack:crud`

We can improve every little one of those. And we will, it's IMPORTANT. But after we do that... what we should really _really_ do... is move the video/text/email course to later in the process. If we do that, we can reduce the time-to-wow from 30 minutes... down to 3-5 minutes. Now THAT is a huge onboarding improvement.

**Comment by kasperbjerby** [comment]
Something I noticed when I just started with it here a couple of weeks ago is that I don't feel like the pro vs free information is good enough.. I got sold by all the features on the front page, they did not say that I had to pay for filters, bulk actions, clone, etc

I install it and start reading the docs, I here notice that some parts are paid and some are free.. But I think that is fine, I don't need most of the paid stuff, so I go ahead and start using it, I get alot done and it is first when I get to adding filters I notice, that they are paid too? I did my research, I looked in the docs (just not good enough), if you look under
 https://backpackforlaravel.com/docs/5.x/crud-operations

It says:
"List - allows the admin to see all entries for an Eloquent model, with pagination, search, filters" And then a green box whit the text "FREE"

And even if you go under the LIST section of the documentation

https://backpackforlaravel.com/docs/5.x/crud-operation-list-entries

It mentions filters again, but it does not mention its a paid feature.. Only if you manually go under the "Filters" section itself to see how you go about using that feature, then it says "PRO"

I can just remember that I got a little "mehh" feeling when I noticed that, and mostly because of how I noticed that..

So I would suggest, look at everything that is free and that is paid and make sure there is no way people can get the understanding that something is free, and then later get a surprise that they have to pay

Just my 2 cents 🤗
Great job on backpack btw

**Comment by tabacitu** [comment]
> So I would suggest, look at everything that is free and that is paid and make sure there is no way people can get the understanding that something is free, and then later get a surprise that they have to pay

Thanks so much @kasperbjerby . I've just added PRO notices in those two places in the docs where you noticed we didn't - that wasn't intentional, of course. I'll think of a way to add a PRO notice to the filters in the demo too, thanks 🙏

**Comment by tabacitu** [comment]
I've decided this is good enough already. We can improve this more later on, but I'm downgrading this from a MUST to a SHOULD. We've already done the most impactful changes.
